[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.121.3",
<<<<<<< HEAD
    "pandas>=2.3.3",
    "supabase>=2.25.1",
    "uvicorn>=0.38.0",
]
=======
    "supabase>=2.25.1",
    "uvicorn>=0.38.0",
    "psycopg2-binary>=2.9",
    "pandas",
    "pyfaidx",
    "numpy",
    "tqdm",
    "requests",
    "sqlalchemy>=2.0.46",
    "python-dotenv>=1.2.1",
]


>>>>>>> backend
